package routes

// Middleware
var Testing_Export_authenticate = authenticate
var Testing_Export_getActiveLeague = getActiveLeague
var Testing_Export_getUrlId = getUrlId
var Testing_Export_failIfNoTeamCreatePermissions = failIfNoTeamCreatePermissions
var Testing_Export_failIfNoEditSchedulePermissions = failIfNoEditSchedulePermissions
var Testing_Export_failIfNoReportResultPermissions = failIfNoReportResultPermissions
var Testing_Export_failIfCannotJoinLeague = failIfCannotJoinLeague
var Testing_Export_failIfNotLeagueAdmin = failIfNotLeagueAdmin
var Testing_Export_failIfTeamActive = failIfTeamActive
var Testing_Export_failIfNotTeamAdministrator = failIfNotTeamAdministrator
var Testing_Export_failIfCanNotEditTeamInformation = failIfCanNotEditTeamInformation
var Testing_Export_failIfLeagueDoesNotExist = failIfLeagueDoesNotExist

// Users
var Testing_Export_createNewUser = createNewUser
var Testing_Export_getProfile = getProfile
var Testing_Export_getUserPermissions = getUserPermissions
var Testing_Export_login = login

// Leagues
var Testing_Export_createNewLeague = createNewLeague
var Testing_Export_updateLeagueInfo = updateLeagueInfo
var Testing_Export_joinActiveLeague = joinActiveLeague
var Testing_Export_setActiveLeague = setActiveLeague
var Testing_Export_getActiveLeagueInformation = getActiveLeagueInformation
var Testing_Export_getTeamSummary = getTeamSummary
var Testing_Export_getGameSummary = getGameSummary
var Testing_Export_getTeamManagers = getTeamManagers
var Testing_Export_getPublicLeagues = getPublicLeagues
var Testing_Export_setLeaguePermissions = setLeaguePermissions

// Teams
var Testing_Export_createNewTeam = createNewTeam
var Testing_Export_deleteTeam = deleteTeam
var Testing_Export_updateTeam = updateTeam
var Testing_Export_getTeamInformation = getTeamInformation
var Testing_Export_addPlayerToTeam = addPlayerToTeam
var Testing_Export_removePlayerFromTeam = removePlayerFromTeam
var Testing_Export_updatePlayer = updatePlayer
var Testing_Export_updateManagerPermissions = updateManagerPermissions

// Games
var Testing_Export_createNewGame = createNewGame
var Testing_Export_getGameInformation = getGameInformation
var Testing_Export_reportGameResult = reportGameResult
var Testing_Export_deleteGame = deleteGame
var Testing_Export_rescheduleGame = rescheduleGame
