// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import databaseAccess "esports-league-manager/Backend/Server/databaseAccess"
import mock "github.com/stretchr/testify/mock"

// GamesDAO is an autogenerated mock type for the GamesDAO type
type GamesDAO struct {
	mock.Mock
}

// CreateGame provides a mock function with given fields: leagueId, team1Id, team2Id, gameTime
func (_m *GamesDAO) CreateGame(leagueId int, team1Id int, team2Id int, gameTime int) (int, error) {
	ret := _m.Called(leagueId, team1Id, team2Id, gameTime)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int, int, int) int); ok {
		r0 = rf(leagueId, team1Id, team2Id, gameTime)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int, int) error); ok {
		r1 = rf(leagueId, team1Id, team2Id, gameTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoesExistConflict provides a mock function with given fields: team1Id, team2Id, gameTime
func (_m *GamesDAO) DoesExistConflict(team1Id int, team2Id int, gameTime int) (bool, error) {
	ret := _m.Called(team1Id, team2Id, gameTime)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int, int) bool); ok {
		r0 = rf(team1Id, team2Id, gameTime)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(team1Id, team2Id, gameTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGameInformation provides a mock function with given fields: leagueId, gameId
func (_m *GamesDAO) GetGameInformation(leagueId int, gameId int) (*databaseAccess.GameInformation, error) {
	ret := _m.Called(leagueId, gameId)

	var r0 *databaseAccess.GameInformation
	if rf, ok := ret.Get(0).(func(int, int) *databaseAccess.GameInformation); ok {
		r0 = rf(leagueId, gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*databaseAccess.GameInformation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(leagueId, gameId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasReportResultPermissions provides a mock function with given fields: leagueId, gameId, userId
func (_m *GamesDAO) HasReportResultPermissions(leagueId int, gameId int, userId int) (bool, error) {
	ret := _m.Called(leagueId, gameId, userId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int, int) bool); ok {
		r0 = rf(leagueId, gameId, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(leagueId, gameId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportGame provides a mock function with given fields: leagueId, gameId, winnerId, scoreTeam1, scoreTeam2
func (_m *GamesDAO) ReportGame(leagueId int, gameId int, winnerId int, scoreTeam1 int, scoreTeam2 int) error {
	ret := _m.Called(leagueId, gameId, winnerId, scoreTeam1, scoreTeam2)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int, int, int) error); ok {
		r0 = rf(leagueId, gameId, winnerId, scoreTeam1, scoreTeam2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
