// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import gin "github.com/gin-gonic/gin"
import mock "github.com/stretchr/testify/mock"

// SessionManager is an autogenerated mock type for the SessionManager type
type SessionManager struct {
	mock.Mock
}

// AuthenticateAndGetUserId provides a mock function with given fields: ctx
func (_m *SessionManager) AuthenticateAndGetUserId(ctx *gin.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(*gin.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveLeague provides a mock function with given fields: ctx
func (_m *SessionManager) GetActiveLeague(ctx *gin.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(*gin.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogIn provides a mock function with given fields: ctx, userId
func (_m *SessionManager) LogIn(ctx *gin.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogOut provides a mock function with given fields: ctx
func (_m *SessionManager) LogOut(ctx *gin.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetActiveLeague provides a mock function with given fields: ctx, leagueId
func (_m *SessionManager) SetActiveLeague(ctx *gin.Context, leagueId int) error {
	ret := _m.Called(ctx, leagueId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, int) error); ok {
		r0 = rf(ctx, leagueId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
