package routes

var Testing_Export_authenticate = authenticate
var Testing_Export_getActiveLeague = getActiveLeague
var Testing_Export_getUrlId = getUrlId
var Testing_Export_getTeamEditPermissions = getTeamEditPermissions
var Testing_Export_getReportResultPermissions = getReportResultPermissions

var Testing_Export_createNewUser = createNewUser
var Testing_Export_getProfile = getProfile
var Testing_Export_login = login

var Testing_Export_createNewLeague = createNewLeague
var Testing_Export_setActiveLeague = setActiveLeague
var Testing_Export_getActiveLeagueInformation = getActiveLeagueInformation

var Testing_Export_createNewTeam = createNewTeam
var Testing_Export_getTeamInformation = getTeamInformation

var Testing_Export_createNewGame = createNewGame
var Testing_Export_getGameInformation = getGameInformation
var Testing_Export_reportGameResult = reportGameResult
