// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IconManager is an autogenerated mock type for the IconManager type
type IconManager struct {
	mock.Mock
}

// StoreNewIcon provides a mock function with given fields: tempLoc
func (_m *IconManager) StoreNewIcon(tempLoc string) (string, string, error) {
	ret := _m.Called(tempLoc)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tempLoc)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(tempLoc)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(tempLoc)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
