// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MdManager is an autogenerated mock type for the MdManager type
type MdManager struct {
	mock.Mock
}

// GetMarkdown provides a mock function with given fields: fileName
func (_m *MdManager) GetMarkdown(fileName string) (string, error) {
	ret := _m.Called(fileName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreMarkdown provides a mock function with given fields: leagueId, _a1, oldFile
func (_m *MdManager) StoreMarkdown(leagueId int, _a1 string, oldFile string) (string, error) {
	ret := _m.Called(leagueId, _a1, oldFile)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, string, string) string); ok {
		r0 = rf(leagueId, _a1, oldFile)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(leagueId, _a1, oldFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
