// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import sql "database/sql"

// RowArr is an autogenerated mock type for the RowArr type
type RowArr struct {
	mock.Mock
}

// Scan provides a mock function with given fields: _a0
func (_m *RowArr) Scan(_a0 *sql.Rows) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Rows) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
